# Generated by Django 6.0.4 on 2026-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitraininglog',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aitraininglog',
            name='corrected_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aitraininglog',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aitraininglog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
