# Generated by Django 6.0.4 on 2026-04-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_aitraininglog_user_alter_aitraininglog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitraininglog',
            name='assigned_team',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('AI/ML', 'AI/ML')], default='Backend', max_length=20),
        ),
        migrations.AddField(
            model_name='aitraininglog',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='aitraininglog',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='aitraininglog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aitraininglog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
