# Generated by Django 4.2.30 on 2026-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0004_aitraininglog_assigned_team_aitraininglog_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitraininglog',
            name='priority',
            field=models.CharField(choices=[('P3', 'P3 - Standard'), ('P2', 'P2 - Important'), ('P1', 'P1 - Critical')], default='P3', max_length=15),
        ),
    ]
