# Generated by Django 4.2.30 on 2026-04-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_portal', '0005_alter_aitraininglog_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_text', models.TextField()),
                ('classification', models.CharField(max_length=100)),
                ('category_code', models.IntegerField()),
                ('system_certainty', models.FloatField(default=0.0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('override_category', models.CharField(blank=True, max_length=100, null=True)),
                ('override_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('assigned_team', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Intelligent Triage', 'Intelligent Triage')], default='Backend', max_length=25)),
                ('priority', models.CharField(choices=[('P3', 'P3 - Standard'), ('P2', 'P2 - Important'), ('P1', 'P1 - Critical')], default='P3', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AITrainingLog',
        ),
    ]
