# Generated by Django 4.2.30 on 2026-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_supportcase_delete_aitraininglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcase',
            name='assigned_team',
            field=models.CharField(choices=[('Infrastructure Ops', 'Infrastructure Ops'), ('Interface Engineering', 'Interface Engineering'), ('Core Logic Layer', 'Core Logic Layer'), ('Security & Identity', 'Security & Identity')], default='Infrastructure Ops', max_length=50),
        ),
    ]
