# Generated by Django 4.2.30 on 2026-04-12 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_portal', '0007_alter_supportcase_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='assigned_team',
            field=models.CharField(choices=[('Infrastructure Ops', 'Infrastructure Ops'), ('Interface Engineering', 'Interface Engineering'), ('Data Analytics Layer', 'Data Analytics Layer')], default='Infrastructure Ops', max_length=50),
        ),
    ]
