# Generated by Django 4.2.30 on 2026-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0008_supportcase_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcase',
            name='assigned_team',
            field=models.CharField(choices=[('Systems Engine', 'Systems Engine'), ('Creative Architecture', 'Creative Architecture'), ('Neural Insights', 'Neural Insights')], default='Infrastructure Ops', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Open', max_length=20),
        ),
    ]
