# Generated by Django 4.2.30 on 2026-04-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0009_alter_supportcase_assigned_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcase',
            name='triage_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
