# Generated by Django 6.0.4 on 2026-04-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtestprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
