# Generated by Django 4.2.30 on 2026-04-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developer_dashboard', '0002_alter_abtestprediction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_a', models.TextField()),
                ('strategy_b', models.TextField()),
                ('comparison_result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ABTestPrediction',
        ),
    ]
