# Generated by Django 4.2.30 on 2026-04-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer_dashboard', '0003_strategiccomparison_delete_abtestprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrategicComparison',
        ),
    ]
